---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuer
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/issuer/test
  dependsOn:
    - name: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: linkerd-identity-issuer
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bcloud
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/buoyant
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - kind: DaemonSet
      name: buoyant-cloud-metrics
      namespace: linkerd-buoyant
  patches:
    - patch: |-
        - op: add
          path: /spec/values/metadata
          value: 
            agentName: "dev"
      target:
        kind: HelmRelease
        name: linkerd-buoyant
        namespace: linkerd-buoyant
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/linkerd
  dependsOn:
    - name: issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  postBuild:
    substituteFrom:
      - kind: Secret
        name: linkerd-enterprise
  patches:
    - patch: |-
        - op: replace
          path: /spec/components/linkerd/controlPlaneConfig/identityTrustAnchorsPEM
          value: |
            -----BEGIN CERTIFICATE-----
            MIIBjTCCATSgAwIBAgIRALqCjmAbjhY38Mlbaq5n2+MwCgYIKoZIzj0EAwIwJTEj
            MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjQwMjA4MjEy
            NTUwWhcNMzQwMjA1MjEyNTUwWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
            c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABICf1Yd8Vtw/SdUd
            rsy/DDhCGTyA55eeZ531nxqLa/1DGfVwzDptJRcQkuo8JvQawRojPC6fTn4wbyWs
            35VCdPyjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
            A1UdDgQWBBRg43tlfGkcuLVAra9bukRbnclBRjAKBggqhkjOPQQDAgNHADBEAiBW
            k6FpcUT412LwSy+oCfMk+ktDthqcH9JDfwrPKG0Q3wIgSP71Kk0N5kmiZrTrW5Sm
            hi0M1g5eUQUwZmqLEF/DAdo=
            -----END CERTIFICATE-----
      target:
        kind: ControlPlane
        name: linkerd-control-plane
  healthChecks:
    - kind: Deployment
      name: linkerd-identity
      namespace: linkerd
    - kind: Deployment
      name: linkerd-destination
      namespace: linkerd
    - kind: Deployment
      name: linkerd-proxy-injector
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emojivoto
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/source/emojivoto
  dependsOn:
    - name: linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: emoji
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: vote-bot
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: web
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: voting
      namespace: emojivoto
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dataplanes
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/source/dataplanes
  prune: true
  dependsOn:
    - name: emojivoto
  sourceRef:
    kind: GitRepository
    name: 59s