---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuer
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/issuer/test
  dependsOn:
    - name: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: linkerd-identity-issuer
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bcloud
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/buoyant
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - kind: DaemonSet
      name: buoyant-cloud-metrics
      namespace: linkerd-buoyant
  patches:
    - patch: |-
        - op: add
          path: /spec/values/metadata
          value: 
            agentName: "dev"
      target:
        kind: HelmRelease
        name: linkerd-buoyant
        namespace: linkerd-buoyant
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/linkerd
  dependsOn:
    - name: issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  postBuild:
    substituteFrom:
      - kind: Secret
        name: linkerd-enterprise
  healthChecks:
    - kind: Deployment
      name: linkerd-identity
      namespace: linkerd
    - kind: Deployment
      name: linkerd-destination
      namespace: linkerd
    - kind: Deployment
      name: linkerd-proxy-injector
      namespace: linkerd