apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-buoyant
  namespace: linkerd-buoyant
spec:
  timeout: 3m
  interval: 10m
  releaseName: linkerd-buoyant
  targetNamespace: linkerd-buoyant
  storageNamespace: linkerd-buoyant
  chart:
    spec:
      chart: linkerd-buoyant
      version: 0.26.1
      sourceRef:
        kind: HelmRepository
        name: linkerd-buoyant
        namespace: linkerd-buoyant
      interval: 40m
  values:
    installNamespace: false
  valuesFrom:
    - kind: Secret
      name: buoyant-cloud-credentials
      valuesKey: api_client_id
      targetPath: metadata.clientID
    - kind: Secret
      name: buoyant-cloud-credentials
      valuesKey: api_client_secret
      targetPath: metadata.clientSecret
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
