---
apiVersion: linkerd.buoyant.io/v1alpha1
kind: ControlPlane
metadata:
  name: linkerd-control-plane
spec:
  components:
    linkerd:
      version: preview-24.2.1
      license: ${buoyant_license}
      controlPlaneConfig:
        proxy:
          image:
            version: preview-24.2.1-hazl
        identity:
          issuer:
            scheme: kubernetes.io/tls
        destinationController:
          experimentalArgs:
          - -experimental-endpoint-zone-weights
