---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuer
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/issuer/test
  dependsOn:
    - name: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: linkerd-identity-issuer
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bcloud
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/buoyant
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - kind: DaemonSet
      name: buoyant-cloud-metrics
      namespace: linkerd-buoyant
  patches:
    - patch: |-
        - op: add
          path: /spec/values/metadata
          value: 
            agentName: "prod"
      target:
        kind: HelmRelease
        name: linkerd-buoyant
        namespace: linkerd-buoyant
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/linkerd/ha
  dependsOn:
    - name: issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  postBuild:
    substituteFrom:
      - kind: Secret
        name: linkerd-enterprise
  healthChecks:
    - kind: Deployment
      name: linkerd-identity
      namespace: linkerd
    - kind: Deployment
      name: linkerd-destination
      namespace: linkerd
    - kind: Deployment
      name: linkerd-proxy-injector
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/linkerd-viz
  dependsOn:
    - name: linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: linkerd-viz
      namespace: linkerd-viz
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/source/flagger
  dependsOn:
    - name: linkerd-viz
  prune: true
  sourceRef:
    kind: GitRepository
    name: 59s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: flagger
      namespace: flagger
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: emojivoto
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/apps/source/emojivoto
  dependsOn:
    - name: flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: emoji
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: vote-bot
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: web
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: voting
      namespace: emojivoto
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: booksapp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/apps/source/booksapp
  dependsOn:
    - name: flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traffic
      namespace: booksapp
    - apiVersion: apps/v1
      kind: Deployment
      name: webapp
      namespace: booksapp
    - apiVersion: apps/v1
      kind: Deployment
      name: authors
      namespace: booksapp
    - apiVersion: apps/v1
      kind: Deployment
      name: books
      namespace: booksapp