apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: nginx-ingress
spec:
  timeout: 3m
  interval: 40m
  releaseName: ingress
  targetNamespace: nginx-ingress
  storageNamespace: nginx-ingress
  chart:
    spec:
      chart: nginx
      version: 17.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: nginx-ingress
      interval: 40m
  values:
    podAnnotations:
      linkerd.io/inject: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: nginx-ingress
spec:
  interval: 2m
  url: https://charts.bitnami.com/bitnami
---
kind: Namespace
apiVersion: v1
metadata:
  name: nginx-ingress